name: codebreakers
version: 0.5.4.2
summary: Guess the code and unlock RogueBot Central
description: Game similar to mastermind, pit yourself against progressively harder codes as you try to unlock new areas, and puzzle types
confinement: strict

apps:
  codebreakers:
    command: codebreakers.wrapper
    plugs: [unity7,opengl,x11,pulseaudio,home]

parts:
  codebreakers:
    plugin: dump
    source: deploy/
    stage-packages:
      - ubuntu-sdk-libs
      - qtubuntu-desktop
      - qtmir-desktop
      - mir-graphics-drivers-desktop



