name: codebreakers
version: 0.5.4.8
summary: Guess the code and unlock RogueBot Central
description: Digital escape room game where you pit yourself against progressively harder codes as you try to unlock new areas, and puzzle types.
confinement: strict

apps:
  codebreakers:
    command: desktop-launch $SNAP/bin/codebreakers
    plugs: [unity7,opengl,x11,pulseaudio,network,process-control]

parts:
  codebreakers:
    plugin: dump
    source: deploy/
    stage-packages:
      - ubuntu-sdk-libs
    after: [desktop-qt5]


